[profile.default]
auto_detect_solc = true
src = 'src'
out = 'out'
libs = ['lib']
# eth_rpc_url = 'https://eth-mainnet.alchemyapi.io/v2/PToNmBre9DOHilhG0OcK7I3w5V4lY47L'
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
kinto = "${KINTO_RPC_URL}"

[etherscan]
# goerli = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 16