[profile.default]
auto_detect_solc = true
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
# Adding evm version because of this https://github.com/foundry-rs/foundry/issues/4988
# evm_version = 'shanghai' # EVM version to use during tests

[rpc_endpoints]
kinto = "${KINTO_RPC_URL}"

[etherscan]
# goerli = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 16