name: Install dependencies
description: Install foundry & other dependencies for use in other actions

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: yarn install

