name: Forge format

on:
  workflow_call:

jobs:
  forge-fmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - uses: ./.github/actions/install
    
      - name: Check formatting
        run: forge fmt --check