name: Push

on:
  push:
    branches:
      - main

jobs:
  forge-mainnet-test:
    name: Forge mainnet tests
    uses: ./.github/workflows/forge-mainnet-test.yml
    secrets: inherit

  certora:
    name: Certora Verification
    uses: ./.github/workflows/certora.yml
    secrets: inherit