name: Slither Analysis

on:
  workflow_call:

jobs:
  analyze:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        id: slither
        continue-on-error: true
        with:
          node-version: 16
          fail-on: none
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

      - name: Comment on failure
        if: steps.slither.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const comment = `❌ Slither analysis failed. Please check the workflow logs for more details.`;
            const repo = context.repo;
            if (issue_number) {
              await github.rest.issues.createComment({
                ...repo,
                issue_number,
                body: comment
              });
            }

      - name: Create/update checklist as PR comment
        if: steps.slither.outcome != 'failure'
        uses: actions/github-script@v6
        env:
          REPORT: ${{ steps.slither.outputs.stdout }}
        with:
          script: |
            const script = require('.github/scripts/comment')
            const header = '# Slither report'
            const body = process.env.REPORT
            await script({ github, context, header, body })
